# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: NYU K-12 Summer Machine Learning

description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the NYU K-12 Summer Machine Learning Program website! Our innovative program introduces young learners to the exciting world of machine learning and artificial intelligence. Through hands-on projects, interactive lessons, and expert mentorship, students will explore the fundamentals of coding, data analysis, and algorithm development. Designed for K-12 students with varying levels of experience, our curriculum fosters critical thinking and problem-solving skills in a collaborative and supportive environment. Join us this summer to embark on a journey of discovery and technological advancement at NYU!

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /:categories/:title/
search: true
# logo: "/assets/images/nyu-logo.jpg"
include:
  - _pages